import { createHash, createHmac, randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { encryptPrivateJson, decryptPrivateJson } from '../crypto/private-data.mjs';

const normalizeBn = value => String(value || '').toUpperCase().replace(/[\s-]/g, '');
function stable(value) {
  if (Array.isArray(value)) return `[${value.map(stable).join(',')}]`;
  if (value && typeof value === 'object') return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${stable(value[key])}`).join(',')}}`;
  return JSON.stringify(value ?? null);
}
function publicOrg(row) {
  if (!row) return null;
  return {id:row.id,tenantId:row.tenant_id,businessNumber:row.business_number,legalName:row.legal_name,organizationType:row.organization_type,province:row.province,publicProfile:row.public_profile||{},createdAt:row.created_at,updatedAt:row.updated_at};
}

export class PostgresStore {
  constructor({databaseUrl,encryptionKey=process.env.ENCRYPTION_KEY,auditHmacKey=process.env.AUDIT_HMAC_KEY}={}) {
    if(!databaseUrl) throw new Error('DATABASE_URL is required for workflow persistence.');
    this.pool=new Pool({connectionString:databaseUrl,max:Number(process.env.DB_POOL_MAX||10)});
    this.encryptionKey=encryptionKey;this.auditHmacKey=auditHmacKey;
  }
  async close(){await this.pool.end();}
  async query(text,params=[]){return this.pool.query(text,params);}
  async tx(fn){const client=await this.pool.connect();try{await client.query('BEGIN');const value=await fn(client);await client.query('COMMIT');return value;}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}

  async ensureUser(identity,client=this.pool){const{rows}=await client.query(`INSERT INTO users(oidc_subject,email,display_name) VALUES($1,$2,$3) ON CONFLICT(oidc_subject) DO UPDATE SET email=EXCLUDED.email,display_name=EXCLUDED.display_name RETURNING *`,[identity.sub,identity.email||null,identity.name||null]);return rows[0];}
  async findOrganizationByBn(value,client=this.pool){const{rows}=await client.query('SELECT * FROM organizations WHERE business_number=$1',[normalizeBn(value)]);return publicOrg(rows[0]);}
  async findOrganizationById(id,client=this.pool){const{rows}=await client.query('SELECT * FROM organizations WHERE id=$1',[id]);return publicOrg(rows[0]);}
  async getOrganizationInternal(idOrBn,client=this.pool){const looksBn=!String(idOrBn).includes('-')||/RR\d{4}$/i.test(String(idOrBn));const{rows}=looksBn?await client.query('SELECT * FROM organizations WHERE business_number=$1',[normalizeBn(idOrBn)]):await client.query('SELECT * FROM organizations WHERE id=$1',[idOrBn]);const row=rows[0];if(!row)return null;return{...publicOrg(row),privateProfile:decryptPrivateJson(row.private_profile||{},this.encryptionKey)};}

  async upsertOrganization({businessNumber=null,legalName,organizationType,province=null,publicProfile={},privateProfile,tenantId=null},actor=null){
    const bn=businessNumber?normalizeBn(businessNumber):null;
    return this.tx(async client=>{const prior=bn?await this.findOrganizationByBn(bn,client):null;const privateEnvelope=privateProfile===undefined?null:encryptPrivateJson(privateProfile,this.encryptionKey);let rows;
      if(prior){({rows}=await client.query(`UPDATE organizations SET legal_name=$2,organization_type=$3,province=$4,public_profile=$5::jsonb,private_profile=CASE WHEN $6::jsonb IS NULL THEN private_profile ELSE $6::jsonb END,updated_at=now() WHERE id=$1 RETURNING *`,[prior.id,legalName,organizationType,province,JSON.stringify(publicProfile||{}),privateEnvelope?JSON.stringify(privateEnvelope):null]));}
      else{({rows}=await client.query(`INSERT INTO organizations(tenant_id,business_number,legal_name,organization_type,province,public_profile,private_profile) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb) RETURNING *`,[tenantId,bn,legalName,organizationType,province,JSON.stringify(publicProfile||{}),JSON.stringify(privateEnvelope||{})]));}
      const after=publicOrg(rows[0]);if(actor)await this.audit(client,actor,after.id,prior?'organization.updated':'organization.created','organization',after.id,{before:prior,after});return after;});
  }
  async updateOrganizationPrivateProfile(orgId,mutator,actor){return this.tx(async client=>{const{rows}=await client.query('SELECT * FROM organizations WHERE id=$1 FOR UPDATE',[orgId]);if(!rows[0])throw new Error('Organization not found.');const before=decryptPrivateJson(rows[0].private_profile||{},this.encryptionKey);const after=await mutator(structuredClone(before));const envelope=encryptPrivateJson(after,this.encryptionKey);await client.query('UPDATE organizations SET private_profile=$2::jsonb,updated_at=now() WHERE id=$1',[orgId,JSON.stringify(envelope)]);await this.audit(client,actor,orgId,'organization.private_profile.updated','organization',orgId,{changedKeys:Object.keys(after||{})});return after;});}

  async membershipsForUser(userId,client=this.pool){const{rows}=await client.query(`SELECT m.role,m.organization_id,o.business_number,o.legal_name,o.organization_type FROM memberships m LEFT JOIN organizations o ON o.id=m.organization_id WHERE m.user_id=$1`,[userId]);return rows.map(row=>({role:row.role,organizationId:row.organization_id,businessNumber:row.business_number,legalName:row.legal_name,organizationType:row.organization_type}));}
  async grantMembership({userId,organizationId,role},actor){return this.tx(async client=>{await client.query('INSERT INTO memberships(user_id,organization_id,role) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[userId,organizationId,role]);await this.audit(client,actor,organizationId,'membership.granted','membership',`${userId}:${organizationId}:${role}`,{userId,organizationId,role});return{userId,organizationId,role};});}
  async createRecipientClaim({organizationId,userId,evidence={},verificationMethod='operator_review'},actor){return this.tx(async client=>{const{rows}=await client.query(`INSERT INTO recipient_claims(organization_id,claimed_by,status,verification_method,evidence) VALUES($1,$2,'pending',$3,$4::jsonb) RETURNING *`,[organizationId,userId,verificationMethod,JSON.stringify(evidence)]);await this.audit(client,actor,organizationId,'recipient_claim.requested','recipient_claim',rows[0].id,{organizationId,userId});return rows[0];});}
  async reviewRecipientClaim({claimId,approve,note=''},actor,recipientAdminRole){return this.tx(async client=>{const{rows}=await client.query('SELECT * FROM recipient_claims WHERE id=$1 FOR UPDATE',[claimId]);const claim=rows[0];if(!claim)throw new Error('Recipient claim not found.');if(claim.status!=='pending')throw new Error(`Recipient claim is already ${claim.status}.`);const status=approve?'verified':'rejected';const evidence={...(claim.evidence||{}),reviewNote:note,reviewedBy:actor.id};await client.query("UPDATE recipient_claims SET status=$2,evidence=$3::jsonb,verified_at=CASE WHEN $2='verified' THEN now() ELSE verified_at END WHERE id=$1",[claimId,status,JSON.stringify(evidence)]);if(approve)await client.query('INSERT INTO memberships(user_id,organization_id,role) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[claim.claimed_by,claim.organization_id,recipientAdminRole]);await this.audit(client,actor,claim.organization_id,`recipient_claim.${status}`,'recipient_claim',claimId,{claimId,status});return{...claim,status,evidence};});}

  async createPlan({foundationOrgId,title,focus='',totalBudgetCad,createdBy},actor){return this.tx(async client=>{const{rows}=await client.query(`INSERT INTO allocation_plans(foundation_org_id,title,focus,total_budget_cad,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *`,[foundationOrgId,title,focus,totalBudgetCad,createdBy]);await this.audit(client,actor,foundationOrgId,'allocation_plan.created','allocation_plan',rows[0].id,rows[0]);return this.getPlan(rows[0].id,client);});}
  async getPlan(planId,client=this.pool){const{rows}=await client.query('SELECT * FROM allocation_plans WHERE id=$1',[planId]);if(!rows[0])return null;const grants=(await client.query('SELECT * FROM grants WHERE plan_id=$1 ORDER BY created_at,id',[planId])).rows;return{...rows[0],grants};}
  async setPlanState({planId,expectedState,nextState,approvedBy=null},actor){return this.tx(async client=>{const{rows}=await client.query('SELECT * FROM allocation_plans WHERE id=$1 FOR UPDATE',[planId]);if(!rows[0])throw new Error('Allocation plan not found.');if(rows[0].state!==expectedState)throw new Error(`Allocation plan must be ${expectedState}; it is ${rows[0].state}.`);const updated=(await client.query(`UPDATE allocation_plans SET state=$2,proposed_at=CASE WHEN $2='proposed' THEN now() ELSE proposed_at END,approved_by=COALESCE($3,approved_by),approved_at=CASE WHEN $2='approved' THEN now() ELSE approved_at END,updated_at=now() WHERE id=$1 RETURNING *`,[planId,nextState,approvedBy])).rows[0];await this.audit(client,actor,updated.foundation_org_id,`allocation_plan.${nextState}`,'allocation_plan',planId,{from:rows[0].state,to:nextState});return this.getPlan(planId,client);});}

  async createGrant({planId,foundationOrgId,recipientOrgId,amountCad,purpose,recipientType,proposedBy=null,rationale='',restrictionType='unrestricted'},actor){return this.tx(async client=>{const plan=planId?(await client.query('SELECT * FROM allocation_plans WHERE id=$1 FOR UPDATE',[planId])).rows[0]:null;if(plan&&plan.state!=='draft')throw new Error('Grants can only be added while an allocation plan is draft.');if(plan){const total=Number((await client.query('SELECT COALESCE(SUM(amount_cad),0) AS total FROM grants WHERE plan_id=$1',[planId])).rows[0].total);if(total+Number(amountCad)>Number(plan.total_budget_cad)+0.005)throw new Error('Grant would exceed the allocation plan budget.');}const{rows}=await client.query(`INSERT INTO grants(plan_id,foundation_org_id,recipient_org_id,amount_cad,purpose,recipient_type,state,proposed_by,rationale,restriction_type) VALUES($1,$2,$3,$4,$5,$6,'draft',$7,$8,$9) RETURNING *`,[planId,foundationOrgId,recipientOrgId,amountCad,purpose,recipientType,proposedBy,rationale,restrictionType]);await this.audit(client,actor,foundationOrgId,'grant.created','grant',rows[0].id,rows[0]);return rows[0];});}
  async getGrant(grantId,client=this.pool){const{rows}=await client.query('SELECT * FROM grants WHERE id=$1',[grantId]);return rows[0]||null;}
  async commitGrantTransition({grantId,expectedState,nextState,actorUserId=null,event,set={}},actor){return this.tx(async client=>{if(event.idempotencyKey){const existing=(await client.query('SELECT * FROM grant_events WHERE idempotency_key=$1',[event.idempotencyKey])).rows[0];if(existing)return{grant:await this.getGrant(grantId,client),event:existing,replayed:true};}const prior=(await client.query('SELECT * FROM grants WHERE id=$1 FOR UPDATE',[grantId])).rows[0];if(!prior)throw new Error('Grant not found.');if(prior.state!==expectedState)throw new Error(`Grant must be ${expectedState}; it is ${prior.state}.`);const proposedBy=set.proposedBy===undefined?prior.proposed_by:set.proposedBy,approvedBy=set.approvedBy===undefined?prior.approved_by:set.approvedBy,acceptedBy=set.acceptedBy===undefined?prior.accepted_by:set.acceptedBy,complianceDecision=set.complianceDecision===undefined?prior.compliance_decision:set.complianceDecision;const grant=(await client.query('UPDATE grants SET state=$2,proposed_by=$3,approved_by=$4,accepted_by=$5,compliance_decision=$6,updated_at=now() WHERE id=$1 RETURNING *',[grantId,nextState,proposedBy,approvedBy,acceptedBy,complianceDecision])).rows[0];const idempotencyKey=event.idempotencyKey||randomUUID();const eventRow=(await client.query(`INSERT INTO grant_events(grant_id,idempotency_key,from_state,to_state,actor_user_id,metadata,occurred_at) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7) RETURNING *`,[grantId,idempotencyKey,expectedState,nextState,actorUserId,JSON.stringify(event.metadata||{}),event.occurredAt||new Date().toISOString()])).rows[0];await this.audit(client,actor,prior.foundation_org_id,`grant.${nextState}`,'grant',grantId,{from:expectedState,to:nextState,eventId:eventRow.id});return{grant,event:eventRow,replayed:false};});}
  async setComplianceDecision(grantId,decision,actor){return this.tx(async client=>{const prior=(await client.query('SELECT * FROM grants WHERE id=$1 FOR UPDATE',[grantId])).rows[0];if(!prior)throw new Error('Grant not found.');const grant=(await client.query('UPDATE grants SET compliance_decision=$2,updated_at=now() WHERE id=$1 RETURNING *',[grantId,decision])).rows[0];await this.audit(client,actor,prior.foundation_org_id,`grant.compliance.${decision}`,'grant',grantId,{prior:prior.compliance_decision,decision});return grant;});}

  async upsertDiligence({grantId,assessment,recommendedRisk},actor){return this.tx(async client=>{const grant=await this.getGrant(grantId,client);if(!grant)throw new Error('Grant not found.');const row=(await client.query(`INSERT INTO grantee_diligence(grant_id,assessment,recommended_risk,status,prepared_by) VALUES($1,$2::jsonb,$3,'draft',$4) ON CONFLICT(grant_id) DO UPDATE SET assessment=EXCLUDED.assessment,recommended_risk=EXCLUDED.recommended_risk,status='draft',prepared_by=EXCLUDED.prepared_by,approved_by=NULL,updated_at=now() RETURNING *`,[grantId,JSON.stringify(assessment),recommendedRisk,actor.id])).rows[0];await this.audit(client,actor,grant.foundation_org_id,'grantee_diligence.prepared','grantee_diligence',grantId,{recommendedRisk});return row;});}
  async getDiligence(grantId,client=this.pool){return(await client.query('SELECT * FROM grantee_diligence WHERE grant_id=$1',[grantId])).rows[0]||null;}
  async approveDiligence(grantId,actor){return this.tx(async client=>{const prior=(await client.query('SELECT * FROM grantee_diligence WHERE grant_id=$1 FOR UPDATE',[grantId])).rows[0];if(!prior)throw new Error('Diligence record not found.');if(prior.prepared_by===actor.id)throw new Error('Separation of duties: diligence preparer cannot approve the same record.');const row=(await client.query("UPDATE grantee_diligence SET status='approved',approved_by=$2,updated_at=now() WHERE grant_id=$1 RETURNING *",[grantId,actor.id])).rows[0];const grant=await this.getGrant(grantId,client);await this.audit(client,actor,grant.foundation_org_id,'grantee_diligence.approved','grantee_diligence',grantId,{approvedBy:actor.id});return row;});}

  async recordStatusCheck({organizationId,source,sourceRecordId=null,status,evidence={},verifiedAt=new Date(),expiresAt=null},actor){return this.tx(async client=>{const row=(await client.query(`INSERT INTO recipient_status_checks(organization_id,source,source_record_id,status,evidence,verified_at,expires_at) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7) RETURNING *`,[organizationId,source,sourceRecordId,status,JSON.stringify(evidence),verifiedAt,expiresAt])).rows[0];await this.audit(client,actor,organizationId,`recipient_status.${status}`,'recipient_status_check',row.id,{source,sourceRecordId,status});return row;});}
  async latestStatusCheck(organizationId,client=this.pool){return(await client.query('SELECT * FROM recipient_status_checks WHERE organization_id=$1 ORDER BY verified_at DESC LIMIT 1',[organizationId])).rows[0]||null;}

  async createOfferToken({grantId,tokenHash,expiresAt},actor){return this.tx(async client=>{await client.query('UPDATE offer_access_tokens SET used_at=COALESCE(used_at,now()) WHERE grant_id=$1 AND used_at IS NULL',[grantId]);const row=(await client.query('INSERT INTO offer_access_tokens(grant_id,token_hash,expires_at) VALUES($1,$2,$3) RETURNING *',[grantId,tokenHash,expiresAt])).rows[0];const grant=await this.getGrant(grantId,client);await this.audit(client,actor,grant.foundation_org_id,'grant_offer_token.created','grant',grantId,{expiresAt});return row;});}
  async inspectOfferToken(tokenHashValue,client=this.pool){return(await client.query('SELECT * FROM offer_access_tokens WHERE token_hash=$1',[tokenHashValue])).rows[0]||null;}
  async consumeOfferToken(tokenHashValue){return this.tx(async client=>{const row=(await client.query('SELECT * FROM offer_access_tokens WHERE token_hash=$1 FOR UPDATE',[tokenHashValue])).rows[0];if(!row)throw new Error('Invalid offer token.');if(row.used_at)throw new Error('Offer token has already been used.');if(new Date(row.expires_at).getTime()<=Date.now())throw new Error('Offer token has expired.');return(await client.query('UPDATE offer_access_tokens SET used_at=now() WHERE id=$1 RETURNING *',[row.id])).rows[0];});}
  async createConsent({grantId,userId=null,termsVersion,accepted,metadata={},acceptanceMethod='authenticated_user',offerTokenId=null},actor){return this.tx(async client=>{const row=(await client.query(`INSERT INTO recipient_consents(grant_id,user_id,terms_version,accepted,metadata,acceptance_method,offer_token_id) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7) RETURNING *`,[grantId,userId,termsVersion,accepted,JSON.stringify(metadata),acceptanceMethod,offerTokenId])).rows[0];const grant=await this.getGrant(grantId,client);await this.audit(client,actor,grant.foundation_org_id,`recipient_consent.${accepted?'accepted':'declined'}`,'recipient_consent',row.id,{grantId,acceptanceMethod});return row;});}

  async enqueueNotification({grantId,channel,recipient,subject=null,template,payload,idempotencyKey},actor){return this.tx(async client=>{const existing=(await client.query('SELECT * FROM notification_outbox WHERE idempotency_key=$1',[idempotencyKey])).rows[0];if(existing)return existing;const row=(await client.query(`INSERT INTO notification_outbox(grant_id,channel,recipient,subject,template,payload,status,idempotency_key) VALUES($1,$2,$3,$4,$5,$6::jsonb,'queued',$7) RETURNING *`,[grantId,channel,recipient,subject,template,JSON.stringify(payload),idempotencyKey])).rows[0];const grant=grantId?await this.getGrant(grantId,client):null;await this.audit(client,actor,grant?.foundation_org_id||null,'notification.queued','notification',row.id,{grantId,channel});return row;});}
  async markNotification({id,status,providerMessageId=null,lastError=null},actor){return this.tx(async client=>{const row=(await client.query(`UPDATE notification_outbox SET status=$2,provider_message_id=$3,last_error=$4,sent_at=CASE WHEN $2='sent' THEN now() ELSE sent_at END WHERE id=$1 RETURNING *`,[id,status,providerMessageId,lastError])).rows[0];const grant=row?.grant_id?await this.getGrant(row.grant_id,client):null;await this.audit(client,actor,grant?.foundation_org_id||null,`notification.${status}`,'notification',id,{providerMessageId,lastError});return row;});}

  async createPaymentIntent({grantId,provider,amountCad,createdBy},actor){return this.tx(async client=>{const existing=(await client.query('SELECT * FROM payment_intents WHERE grant_id=$1',[grantId])).rows[0];if(existing)return existing;const row=(await client.query(`INSERT INTO payment_intents(grant_id,provider,amount_cad,status,created_by) VALUES($1,$2,$3,'created',$4) RETURNING *`,[grantId,provider,amountCad,createdBy])).rows[0];const grant=await this.getGrant(grantId,client);await this.audit(client,actor,grant.foundation_org_id,'payment_intent.created','payment_intent',row.id,{grantId,amountCad,provider});return row;});}
  async getPaymentIntent(id,client=this.pool){return(await client.query('SELECT * FROM payment_intents WHERE id=$1',[id])).rows[0]||null;}
  async authorizePaymentIntent({id,authorizedBy,status='external_execution_required'},actor){return this.tx(async client=>{const prior=(await client.query('SELECT * FROM payment_intents WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!prior)throw new Error('Payment intent not found.');if(prior.created_by&&prior.created_by===authorizedBy)throw new Error('Separation of duties: payment-intent creator cannot authorize the same payment intent.');if(prior.status!=='created')throw new Error(`Payment intent must be created; it is ${prior.status}.`);const row=(await client.query('UPDATE payment_intents SET status=$2,authorized_by=$3,authorized_at=now() WHERE id=$1 RETURNING *',[id,status,authorizedBy])).rows[0];const grant=await this.getGrant(row.grant_id,client);await this.audit(client,actor,grant.foundation_org_id,'payment_intent.authorized','payment_intent',id,{status});return row;});}
  async recordPaymentIntent({id,externalReference},actor){return this.tx(async client=>{const prior=(await client.query('SELECT * FROM payment_intents WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!prior)throw new Error('Payment intent not found.');if(prior.status!=='external_execution_required')throw new Error(`Payment intent must require external execution; it is ${prior.status}.`);const row=(await client.query("UPDATE payment_intents SET status='recorded',external_reference=$2,recorded_at=now() WHERE id=$1 RETURNING *",[id,externalReference])).rows[0];const grant=await this.getGrant(row.grant_id,client);await this.audit(client,actor,grant.foundation_org_id,'payment_intent.recorded','payment_intent',id,{externalReference});return row;});}

  async grantsForRecipientFiscalYear(recipientOrgId,fiscalYear){const start=`${fiscalYear}-01-01T00:00:00.000Z`,end=`${fiscalYear+1}-01-01T00:00:00.000Z`;return(await this.pool.query("SELECT * FROM grants WHERE recipient_org_id=$1 AND created_at >= $2 AND created_at < $3 AND state NOT IN ('declined','cancelled')",[recipientOrgId,start,end])).rows;}
  async createReportingRecord({grantId,fiscalYear,reportingRoute,t3010Version,t1441Required,payload},actor){return this.tx(async client=>{const row=(await client.query(`INSERT INTO reporting_records(grant_id,fiscal_year,reporting_route,t3010_version,t1441_required,payload,status) VALUES($1,$2,$3,$4,$5,$6::jsonb,'ready') RETURNING *`,[grantId,fiscalYear,reportingRoute,t3010Version,t1441Required,JSON.stringify(payload)])).rows[0];const grant=await this.getGrant(grantId,client);await this.audit(client,actor,grant.foundation_org_id,'reporting_record.ready','reporting_record',row.id,{grantId,reportingRoute,t1441Required});return row;});}
  async markReportingFiled({id,filingReference},actor){return this.tx(async client=>{const prior=(await client.query('SELECT * FROM reporting_records WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!prior)throw new Error('Reporting record not found.');const payload={...(prior.payload||{}),filingReference};const row=(await client.query("UPDATE reporting_records SET status='filed',payload=$2::jsonb,updated_at=now() WHERE id=$1 RETURNING *",[id,JSON.stringify(payload)])).rows[0];const grant=await this.getGrant(row.grant_id,client);await this.audit(client,actor,grant.foundation_org_id,'reporting_record.filed','reporting_record',id,{filingReference});return row;});}

  async audit(client,actor,organizationId,action,resourceType,resourceId,payload={}){if(!this.auditHmacKey)throw new Error('AUDIT_HMAC_KEY is required for workflow writes.');const prior=(await client.query('SELECT entry_hmac FROM audit_log ORDER BY sequence DESC LIMIT 1')).rows[0];const previousDigest=prior?.entry_hmac||null;const canonical=stable({actorId:actor?.id||null,action,resourceType,resourceId,organizationId,payload});const payloadDigest=createHash('sha256').update(canonical).digest('hex');const entryHmac=createHmac('sha256',this.auditHmacKey).update(`${previousDigest||''}|${payloadDigest}|${action}|${resourceType}|${resourceId}`).digest('hex');await client.query(`INSERT INTO audit_log(actor_user_id,organization_id,action,resource_type,resource_id,payload_digest,previous_digest,entry_hmac) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[actor?.id&&/^[0-9a-f-]{36}$/i.test(actor.id)?actor.id:null,organizationId,action,resourceType,String(resourceId),payloadDigest,previousDigest,entryHmac]);}
  async listAudit({limit=100,resourceType=null,resourceId=null}={}){const params=[],where=[];if(resourceType){params.push(resourceType);where.push(`resource_type=$${params.length}`);}if(resourceId){params.push(String(resourceId));where.push(`resource_id=$${params.length}`);}params.push(Math.min(Math.max(Number(limit)||100,1),500));return(await this.pool.query(`SELECT * FROM audit_log ${where.length?`WHERE ${where.join(' AND ')}`:''} ORDER BY sequence DESC LIMIT $${params.length}`,params)).rows;}
}
