import { z } from 'zod';
import { calculateTieredDQ,calculateFlatScenarioDQ,investmentScenario } from '../domain/dq.mjs';
import { capacitySaved } from '../domain/capacity.mjs';
import { nationalAllocationScenario } from '../matching/allocation.mjs';
import { ingestT3010 } from '../t3010/importer.mjs';
import { DEFAULT_T3010_YEAR,RESOURCE_KINDS } from '../t3010/constants.mjs';
import { ROLES } from '../security/rbac.mjs';
import { READ_ONLY,OPEN_READ,WRITE_EXTERNAL,textResult,normalizeBn } from './common.mjs';

export function registerPublicTools(server,{repository,dataDir,config,getLoadError,setLoadError,workflow=null,identity=null}){
 const requireData=()=>{if(!repository.loaded)throw new Error(`T3010 data is not loaded from ${dataDir}. Run npm run ingest:t3010 first. ${getLoadError()?`Last load error: ${getLoadError().message}`:''}`);};
 server.registerTool('dataset_status',{title:'T3010 dataset status',description:'Report which CRA T3010/Open Government dataset is loaded and whether authenticated workflow writes are enabled.',inputSchema:{},annotations:READ_ONLY},async()=>textResult(repository.loaded?'T3010 dataset is loaded.':'T3010 dataset is not loaded.',{...repository.status(),loadError:getLoadError()?.message??null,workflowWritesEnabled:config.enableWorkflowWrites,paymentProvider:config.paymentProvider}));
 server.registerTool('search',{title:'Search Canadian charities and foundations',description:'Search the locally ingested CRA T3010 dataset and return stable fetch ids.',inputSchema:{query:z.string().default(''),entityType:z.enum(['charity','foundation','all']).default('all'),province:z.string().max(3).default(''),limit:z.number().int().min(1).max(50).default(20)},annotations:READ_ONLY},async({query,entityType,province,limit})=>{requireData();const charities=entityType==='foundation'?[]:repository.searchCharities({query,province,limit});const foundations=entityType==='charity'?[]:repository.searchFoundations({query,province,limit});const results=[...charities,...foundations].sort((a,b)=>b.score-a.score).slice(0,limit).map(r=>({id:r.id,title:r.name,bn:r.bn,province:r.province,city:r.city,designation:r.designation,score:r.score}));return textResult(`Found ${results.length} T3010 records.`,{results});});
 server.registerTool('fetch',{title:'Fetch a T3010 charity or foundation',description:'Fetch a filing-derived profile by an id returned from search.',inputSchema:{id:z.string().min(1)},annotations:READ_ONLY},async({id})=>{requireData();const parts=id.split(':');if(parts.length!==3||parts[0]!=='t3010')throw new Error('Expected id t3010:charity:<BN> or t3010:foundation:<BN>');const[,type,bn]=parts;const profile=type==='foundation'?repository.foundationProfile(bn):repository.charityProfile(bn);if(!profile)throw new Error(`No ${type} profile found for ${bn}`);return textResult(`${profile.name||bn} — CRA T3010 filing-derived profile.`,{profile});});
 server.registerTool('search_charities',{title:'Search registered charities',description:'Search T3010 charity identification and program text by mission terms and optional province.',inputSchema:{query:z.string().default(''),province:z.string().max(3).default(''),limit:z.number().int().min(1).max(100).default(25)},annotations:READ_ONLY},async args=>{requireData();const results=repository.searchCharities(args);return textResult(`Found ${results.length} charities.`,{results});});
 server.registerTool('search_foundations',{title:'Search Canadian foundations',description:'Search T3010 private/public foundation filings with historical qualified-donee evidence.',inputSchema:{query:z.string().default(''),province:z.string().max(3).default(''),limit:z.number().int().min(1).max(100).default(25)},annotations:READ_ONLY},async args=>{requireData();const results=repository.searchFoundations(args);return textResult(`Found ${results.length} foundations.`,{results});});
 server.registerTool('get_foundation_dq_record',{title:'Get published foundation DQ record',description:'Return Schedule 8 DQ fields exactly as ingested; no legal interpretation is imposed.',inputSchema:{foundationBn:z.string().min(9)},annotations:READ_ONLY},async({foundationBn})=>{requireData();const profile=repository.foundationProfile(normalizeBn(foundationBn));if(!profile)throw new Error('Foundation not found.');return textResult(`Returned published Schedule 8 fields for ${profile.name||profile.bn}.`,{foundation:{bn:profile.bn,name:profile.name},dqFields:profile.disbursementQuotaFields,numericFields:profile.disbursementQuotaNumeric,sourceYear:profile.sourceYear});});
 server.registerTool('match_foundation_recipients',{title:'Match a foundation to registered charities',description:'Rank recipient candidates from transparent T3010 overlap. This is discovery, not a grant award or legal eligibility decision.',inputSchema:{foundationBn:z.string().min(9),focus:z.string().default(''),province:z.string().max(3).default(''),limit:z.number().int().min(1).max(100).default(25)},annotations:READ_ONLY},async args=>{requireData();const result=repository.matchFoundation({...args,foundationBn:normalizeBn(args.foundationBn)});return textResult(`Generated ${result.matches.length} transparent recipient matches. No grants were awarded.`,result);});
 server.registerTool('calculate_foundation_dq',{title:'Calculate planning DQ',description:'Calculate a planning-level DQ from explicit eligible-property assumptions. Not filing advice.',inputSchema:{eligiblePropertyCad:z.number().nonnegative(),mode:z.enum(['tiered','flat_scenario']).default('tiered'),flatRate:z.number().min(0).max(1).default(0.05)},annotations:READ_ONLY},async({eligiblePropertyCad,mode,flatRate})=>{const dqCad=mode==='tiered'?calculateTieredDQ(eligiblePropertyCad):calculateFlatScenarioDQ(eligiblePropertyCad,flatRate);return textResult(`Planning DQ scenario: CAD ${dqCad.toLocaleString('en-CA',{maximumFractionDigits:0})}.`,{eligiblePropertyCad,mode,dqCad,legalStatus:'planning_scenario_not_filing_advice'});});
 server.registerTool('model_foundation_capital',{title:'Model foundation capital',description:'Model gross returns, disbursements and closing assets under explicit assumptions.',inputSchema:{assetPoolCad:z.number().positive(),annualReturn:z.number().min(-1).max(2),dqRate:z.number().min(0).max(1),years:z.number().int().min(1).max(50).default(5)},annotations:READ_ONLY},async args=>textResult('Computed capital/disbursement scenario.',investmentScenario(args.assetPoolCad,args.annualReturn,args.dqRate,args.years)));
 server.registerTool('national_allocation_scenario',{title:'Model national clearing-house capacity',description:'Apply the explicit national planning scenario to foundation assets, return, DQ rate and recipient counts.',inputSchema:{foundationAssetsCad:z.number().positive().default(135_000_000_000),annualReturn:z.number().min(-1).max(2).default(0.085),dqRate:z.number().min(0).max(1).default(0.05),registeredCharities:z.number().int().positive().default(87_000),additionalDoneeShare:z.number().min(0).max(5).default(0.20)},annotations:READ_ONLY},async args=>textResult('Computed national allocation scenario from explicit assumptions.',nationalAllocationScenario(args)));
 server.registerTool('estimate_admin_capacity_saved',{title:'Estimate administrative capacity saved',description:'Apply explicit hours-saved assumptions to a number of grant transactions.',inputSchema:{transactions:z.number().int().nonnegative(),nonprofitHours:z.number().nonnegative().default(40),foundationHours:z.number().nonnegative().default(12),governmentHours:z.number().nonnegative().default(1)},annotations:READ_ONLY},async({transactions,nonprofitHours,foundationHours,governmentHours})=>{const result=capacitySaved(transactions,{nonprofit:nonprofitHours,foundation:foundationHours,government:governmentHours});return textResult(`Estimated ${result.totalHours.toLocaleString()} administrative hours recovered.`,result);});
 if(workflow)server.registerTool('check_recipient_status_evidence',{title:'Check CRA public recipient-status evidence',description:'Read current public CRA revocation evidence for a registered-charity BN. Absence from revocations is not proof of current eligibility and does not update the payment gate.',inputSchema:{recipientBn:z.string().min(9)},annotations:OPEN_READ},async({recipientBn})=>textResult('Checked current CRA public evidence; no workflow eligibility decision was written.',await workflow.publicStatusEvidence(recipientBn)));
 if(config.enableT3010Sync)server.registerTool('sync_t3010',{title:'Synchronize CRA T3010 open data',description:'System-admin-only Open Government Canada T3010 synchronization. Requires exact confirmation.',inputSchema:{year:z.number().int().min(2000).max(2100).default(DEFAULT_T3010_YEAR),datasetId:z.string().uuid().optional(),resources:z.array(z.enum(RESOURCE_KINDS)).default(RESOURCE_KINDS),maxRows:z.number().int().min(0).max(1_000_000).default(0),confirmation:z.string()},annotations:WRITE_EXTERNAL},async({year,datasetId,resources,maxRows,confirmation})=>{if(!identity?.roles?.includes(ROLES.SYSTEM_ADMIN))throw new Error('System administrator role is required.');if(confirmation!==`SYNC T3010 ${year}`)throw new Error(`Explicit confirmation required: SYNC T3010 ${year}`);const manifest=await ingestT3010({year,datasetId,outputDir:dataDir,resources,maxRows});await repository.load({force:true});setLoadError(null);return textResult(`Synchronized ${manifest.resources.length} T3010 resources for ${year}.`,{manifest,status:repository.status()});});
 server.registerTool('open_canada_catalogue',{title:'Open Canada T3010 source metadata',description:'Return the canonical Open Government Canada catalogue URL and loaded source status.',inputSchema:{},annotations:OPEN_READ},async()=>textResult('The app ingests CRA List of charities/T3010 data from Open Government Canada.',{source:'Open Government Canada — CRA List of charities / T3010',catalogue:'https://open.canada.ca/data/en/dataset/80c00cdb-1358-415c-bb8b-0de7f12675b8',loaded:repository.status()}));
}
