import http from 'node:http';
import path from 'node:path';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { T3010Repository } from '../t3010/repository.mjs';
import { DEFAULT_T3010_YEAR } from '../t3010/constants.mjs';
import { loadRuntimeConfig,assessReadiness } from '../config/requirements.mjs';
import { authenticateBearer } from '../auth/oidc.mjs';
import { PostgresStore } from '../db/postgres-store.mjs';
import { WorkflowService } from '../workflow/service.mjs';
import { createNotificationAdapter } from '../integrations/notification.mjs';
import { registerPublicTools } from './public-tools.mjs';
import { registerWorkflowTools } from './workflow-tools.mjs';

const VERSION='0.4.0';const config=loadRuntimeConfig();const readiness=assessReadiness(config);if(config.production&&!readiness.ready)throw new Error(`Production readiness failed: ${readiness.blockers.join(' ')}`);if(config.enableWorkflowWrites&&!readiness.ready)throw new Error(`Workflow writes cannot start: ${readiness.blockers.join(' ')}`);
const port=Number(process.env.PORT||3000),defaultYear=Number(process.env.T3010_YEAR||DEFAULT_T3010_YEAR),dataDir=path.resolve(process.env.T3010_DATA_DIR||path.join('data','t3010',String(defaultYear)));const repository=new T3010Repository(dataDir);let loadError=null;try{await repository.load();}catch(error){loadError=error;}
const store=config.databaseUrl?new PostgresStore({databaseUrl:config.databaseUrl,encryptionKey:config.encryptionKey,auditHmacKey:config.auditHmacKey}):null;const workflow=store?new WorkflowService({store,t3010Repository:repository,config,notificationAdapter:createNotificationAdapter(config)}):null;if(config.enableWorkflowWrites&&!workflow)throw new Error('Workflow writes require PostgreSQL persistence.');
function createMcpServer({identity,context}){const server=new McpServer({name:'canadian-philanthropy-clearing-house',version:VERSION},{instructions:['Use CRA T3010/Open Government data for public discovery and transparent matching.','T3010 data is public/self-reported filing evidence, not a live legal eligibility determination.','Workflow writes require authenticated server-side RBAC and organization scope.','Never describe a match or draft as an award; never describe a public revocation-page check as proof of current eligibility.','Recipient consent, compliance approval, fresh operational status verification and payment separation of duties are enforced in code.','The baseline payment adapter cannot initiate a bank transfer; it records external/manual payment references only.','T3010/T1441 reporting tools prepare records but do not submit CRA returns.'].join(' ')});registerPublicTools(server,{repository,dataDir,config,getLoadError:()=>loadError,setLoadError:value=>{loadError=value;},workflow,identity});if(config.enableWorkflowWrites)registerWorkflowTools(server,{workflow,store,context});return server;}
function oauthMetadata(){return{resource:config.publicBaseUrl||`http://localhost:${port}`,authorization_servers:config.oidcIssuer?[config.oidcIssuer]:[],scopes_supported:['role:system_admin','role:foundation_analyst','role:foundation_approver','role:compliance_reviewer','role:recipient_admin','role:payment_operator','role:auditor']};}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function readBody(req,max=32768){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>max)throw Object.assign(new Error('Request body too large.'),{statusCode:413});chunks.push(chunk);}const raw=Buffer.concat(chunks).toString('utf8');if(String(req.headers['content-type']||'').includes('application/json'))return JSON.parse(raw||'{}');return Object.fromEntries(new URLSearchParams(raw).entries());}
function offerHtml({grant,foundation,recipient,access},token){const amount=Number(grant.amount_cad).toLocaleString('en-CA',{style:'currency',currency:'CAD'});return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="referrer" content="no-referrer"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Grant offer</title><style>body{font-family:system-ui,sans-serif;max-width:720px;margin:4rem auto;padding:0 1rem;line-height:1.5}button{padding:.8rem 1.2rem;margin:.5rem .5rem .5rem 0}textarea{width:100%;min-height:7rem}</style><main><h1>Grant offer</h1><p><strong>${escapeHtml(foundation.legalName)}</strong> has offered <strong>${escapeHtml(amount)}</strong> to <strong>${escapeHtml(recipient.legalName)}</strong>.</p><p>${escapeHtml(grant.purpose)}</p><p>This page records acceptance or decline only. It does not collect banking information or move money.</p><form method="post" action="/offers/${encodeURIComponent(grant.id)}/respond"><input type="hidden" name="token" value="${escapeHtml(token)}"><label>Optional note<br><textarea name="note" maxlength="4000"></textarea></label><br><button type="submit" name="decision" value="accept">Accept offer</button><button type="submit" name="decision" value="decline">Decline offer</button></form><p><small>This single-use link expires ${escapeHtml(new Date(access.expires_at).toISOString())}.</small></p></main></html>`;}
const privacyHtml=`<!doctype html><html lang="en"><meta charset="utf-8"><title>Canadian Philanthropy Clearing House — Privacy</title><body><main><h1>Privacy</h1><p>The discovery layer indexes public CRA T3010 data. Authenticated workflows may process organization contacts, claims, grant decisions, consent, compliance records and external payment references. Private workflow profiles are encrypted at rest by the application.</p><p>The baseline application does not store bank account/card coordinates and does not initiate bank transfers. Production operators must publish their own retention, privacy contact, hosting, subprocessors and incident-response terms.</p></main></body></html>`;

const httpServer=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||`localhost:${port}`}`);
 if(url.pathname==='/'&&req.method==='GET'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({name:'Canadian Philanthropy Clearing House',version:VERSION,mcp:'/mcp',privacy:'/privacy',oauthProtectedResource:'/.well-known/oauth-protected-resource',t3010:repository.status(),workflowWritesEnabled:config.enableWorkflowWrites,readiness}));}
 if(url.pathname==='/healthz'&&req.method==='GET'){res.writeHead(readiness.ready?200:503,{'content-type':'application/json'});return res.end(JSON.stringify({ok:readiness.ready,t3010:repository.status(),loadError:loadError?.message??null,workflowWritesEnabled:config.enableWorkflowWrites,databaseConfigured:Boolean(config.databaseUrl),paymentProvider:config.paymentProvider,readiness}));}
 if(url.pathname==='/privacy'&&req.method==='GET'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(privacyHtml);}
 if(url.pathname==='/.well-known/oauth-protected-resource'&&req.method==='GET'){res.writeHead(200,{'content-type':'application/json','cache-control':'public, max-age=300'});return res.end(JSON.stringify(oauthMetadata()));}
 const offer=url.pathname.match(/^\/offers\/([0-9a-f-]{36})$/i);if(offer&&req.method==='GET'){if(!config.enableWorkflowWrites||!workflow){res.writeHead(404);return res.end('Not found');}const token=url.searchParams.get('token')||'';const details=await workflow.inspectOffer({grantId:offer[1],token});res.writeHead(200,{'content-type':'text/html; charset=utf-8','referrer-policy':'no-referrer','cache-control':'no-store','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'"});return res.end(offerHtml(details,token));}
 const respond=url.pathname.match(/^\/offers\/([0-9a-f-]{36})\/respond$/i);if(respond&&req.method==='POST'){if(!config.enableWorkflowWrites||!workflow){res.writeHead(404);return res.end('Not found');}const body=await readBody(req);if(!['accept','decline'].includes(body.decision))throw Object.assign(new Error('Decision must be accept or decline.'),{statusCode:400});const grant=await workflow.respondByToken({grantId:respond[1],token:String(body.token||''),accept:body.decision==='accept',note:String(body.note||'').slice(0,4000)});res.writeHead(200,{'content-type':'text/html; charset=utf-8','referrer-policy':'no-referrer','cache-control':'no-store','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'"});return res.end(`<!doctype html><html lang="en"><meta charset="utf-8"><title>Response recorded</title><main><h1>${grant.state==='accepted'?'Offer accepted':'Offer declined'}</h1><p>Your response has been recorded. No banking information was requested and no payment was executed by this page.</p></main></html>`);}
 if(url.pathname!=='/mcp'){res.writeHead(404);return res.end('Not found');}
 const identity=await authenticateBearer(req,config);if((config.enableWorkflowWrites||config.enableT3010Sync)&&!identity){res.writeHead(401,{'content-type':'application/json','www-authenticate':`Bearer resource_metadata="${(config.publicBaseUrl||`http://localhost:${port}`).replace(/\/$/,'')}/.well-known/oauth-protected-resource"`});return res.end(JSON.stringify({error:'Authentication required for this MCP deployment.'}));}
 const context=identity&&workflow?await workflow.context(identity):null;const server=createMcpServer({identity,context});const transport=new StreamableHTTPServerTransport({sessionIdGenerator:undefined});res.on('close',()=>transport.close().catch(()=>{}));await server.connect(transport);await transport.handleRequest(req,res);
 }catch(error){const status=error.statusCode||500;if(!res.headersSent)res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify({error:error.message}));}});
httpServer.listen(port,()=>{console.log(`Canadian Philanthropy Clearing House MCP v${VERSION} listening on :${port}/mcp`);if(!repository.loaded)console.warn(`T3010 dataset not loaded from ${dataDir}; search tools will require ingestion.`);if(config.enableWorkflowWrites)console.log('Authenticated PostgreSQL grant workflows enabled.');console.log(`Payment provider: ${config.paymentProvider} (baseline never initiates bank transfers).`);});
