import { z } from 'zod';
import { PERMISSIONS,hasPermission } from '../security/rbac.mjs';
import { READ_ONLY,WRITE_LOCAL,WRITE_EXTERNAL,textResult } from './common.mjs';

export function registerWorkflowTools(server,{workflow,store,context}){
 server.registerTool('my_clearing_house_context',{title:'My clearing-house context',description:'Show the authenticated identity, roles and organization memberships used for workflow authorization.',inputSchema:{},annotations:READ_ONLY},async()=>{if(!context)throw new Error('Authentication required.');return textResult('Authenticated clearing-house context.',{subject:context.identity.sub,email:context.identity.email,tokenRoles:context.identity.roles,tokenOrganizationBns:context.identity.organizationBns,memberships:context.memberships});});
 server.registerTool('admin_upsert_organization',{title:'Create or update workflow organization',description:'System-admin setup of a foundation, registered charity, or non-qualified-donee organization. Private profile data is encrypted at rest.',inputSchema:{businessNumber:z.string().max(30).optional(),legalName:z.string().min(1).max(400),organizationType:z.enum(['foundation','registered_charity','non_qualified_donee','other']),province:z.string().max(10).optional(),publicProfile:z.record(z.any()).default({}),privateProfile:z.record(z.any()).optional()},annotations:WRITE_LOCAL},async input=>textResult('Organization profile saved.',await workflow.upsertOrganization(input,context)));
 server.registerTool('request_recipient_claim',{title:'Request recipient organization claim',description:'Request control of a recipient organization profile. A system administrator must verify the claim before membership is granted.',inputSchema:{businessNumber:z.string().min(9),evidence:z.record(z.any()).default({})},annotations:WRITE_LOCAL},async input=>textResult('Recipient claim requested; administrator verification is required.',await workflow.requestClaim(input,context)));
 server.registerTool('review_recipient_claim',{title:'Review recipient claim',description:'System-admin-only verification or rejection of a recipient claim.',inputSchema:{claimId:z.string().uuid(),approve:z.boolean(),note:z.string().max(4000).default('')},annotations:WRITE_LOCAL},async input=>textResult(input.approve?'Recipient claim verified.':'Recipient claim rejected.',await workflow.reviewClaim(input,context)));
 server.registerTool('update_recipient_profile',{title:'Update reusable recipient profile',description:'Recipient-admin update of reusable public profile and contact coordinates for an organization they control. Contact data is encrypted at rest.',inputSchema:{businessNumber:z.string().min(9),publicProfile:z.record(z.any()).default({}),contact:z.object({email:z.string().email().optional(),phone:z.string().max(50).optional(),website:z.string().url().optional()}).default({})},annotations:WRITE_LOCAL},async input=>textResult('Reusable recipient profile updated.',await workflow.updateRecipientProfile(input,context)));
 server.registerTool('create_allocation_plan',{title:'Create allocation plan',description:'Foundation-analyst creation of an empty draft allocation plan. No recipient is contacted.',inputSchema:{foundationBn:z.string().min(9),title:z.string().min(1).max(400),focus:z.string().max(4000).default(''),totalBudgetCad:z.number().positive()},annotations:WRITE_LOCAL},async input=>textResult('Draft allocation plan created.',await workflow.createPlan(input,context)));
 server.registerTool('draft_matched_allocation_plan',{title:'Draft allocation plan from T3010 matches',description:'Foundation-analyst tool that converts transparent T3010 recipient matches into a budget-constrained draft plan. No award or notification occurs.',inputSchema:{foundationBn:z.string().min(9),title:z.string().min(1).max(400),focus:z.string().max(4000).default(''),province:z.string().max(3).default(''),totalBudgetCad:z.number().positive(),minGrantCad:z.number().positive().default(25000),maxGrantCad:z.number().positive().default(150000),recipientLimit:z.number().int().min(1).max(200).default(50)},annotations:WRITE_LOCAL},async input=>textResult('Matched draft allocation plan created; no offers were sent.',await workflow.draftMatchedPlan(input,context)));
 server.registerTool('add_plan_grant',{title:'Add grant to allocation plan',description:'Add a proposed recipient/amount to a draft plan. Non-qualified donees must already have an operator-created organization profile.',inputSchema:{planId:z.string().uuid(),recipientBn:z.string().min(1),amountCad:z.number().positive(),purpose:z.string().min(1).max(10000),recipientType:z.enum(['qualified_donee','non_qualified_donee']).default('qualified_donee'),rationale:z.string().max(10000).default(''),restrictionType:z.enum(['unrestricted','restricted']).default('unrestricted')},annotations:WRITE_LOCAL},async input=>textResult('Grant added to draft plan.',await workflow.addGrant(input,context)));
 server.registerTool('propose_allocation_plan',{title:'Propose allocation plan',description:'Move every draft grant in the plan to proposed. The proposer cannot later approve the same plan/grants when separation of duties is enabled.',inputSchema:{planId:z.string().uuid()},annotations:WRITE_LOCAL},async({planId})=>textResult('Allocation plan proposed for separate approval.',await workflow.proposePlan(planId,context)));
 server.registerTool('approve_allocation_plan',{title:'Approve allocation plan',description:'Foundation-approver approval of a proposed plan. Non-qualified-donee grants require separately approved diligence; proposer/creator separation of duties is enforced.',inputSchema:{planId:z.string().uuid()},annotations:WRITE_LOCAL},async({planId})=>textResult('Allocation plan approved; recipients have not yet been contacted.',await workflow.approvePlan(planId,context)));
 server.registerTool('get_allocation_plan',{title:'Get allocation plan',description:'Read an allocation plan and its grants when the authenticated user has access to the foundation.',inputSchema:{planId:z.string().uuid()},annotations:READ_ONLY},async({planId})=>{const plan=await store.getPlan(planId);if(!plan)throw new Error('Allocation plan not found.');const foundation=await store.findOrganizationById(plan.foundation_org_id);workflow.actorForOrganization(context,foundation,PERMISSIONS.READ_PRIVATE_ORG);return textResult('Allocation plan retrieved.',plan);});
 server.registerTool('prepare_non_qualified_donee_diligence',{title:'Prepare non-qualified-donee diligence',description:'Document proportional accountability/due diligence for a grant to a non-qualified donee. This supports but does not replace the foundation’s legal/compliance judgment.',inputSchema:{grantId:z.string().uuid(),charitablePurposeAlignment:z.string().min(1).max(10000),activityDescription:z.string().min(1).max(20000),activityLocation:z.string().max(1000).default(''),durationMonths:z.number().int().min(1).max(240).default(12),relationshipExperience:z.enum(['none','some','significant']).default('none'),researchSummary:z.string().max(20000).default(''),writtenAgreement:z.boolean().default(true),reportingPlan:z.enum(['final_report','interim_and_final','custom']).default('final_report'),periodicTransfers:z.boolean().default(false),separateLedger:z.boolean().default(true),notes:z.string().max(20000).default('')},annotations:WRITE_LOCAL},async input=>textResult('Non-qualified-donee diligence prepared and awaiting separate compliance approval.',await workflow.prepareDiligence(input,context)));
 server.registerTool('approve_non_qualified_donee_diligence',{title:'Approve non-qualified-donee diligence',description:'Compliance-reviewer approval of a separately prepared NQD diligence record; preparer/approver separation is enforced.',inputSchema:{grantId:z.string().uuid()},annotations:WRITE_LOCAL},async({grantId})=>textResult('Non-qualified-donee diligence approved.',await workflow.approveDiligence(grantId,context)));
 server.registerTool('record_recipient_status_verification',{title:'Record recipient eligibility/status verification',description:'Compliance-reviewer recording of a current operational eligibility/status verification for a specific grant. This record gates payment authorization.',inputSchema:{grantId:z.string().uuid(),status:z.enum(['eligible','ineligible','unknown','needs_review']),source:z.string().min(1).max(1000),sourceRecordId:z.string().max(1000).optional(),evidence:z.record(z.any()).default({})},annotations:WRITE_LOCAL},async input=>textResult(`Recipient status verification recorded as ${input.status}.`,await workflow.recordStatusVerification(input,context)));
 server.registerTool('approve_grant_compliance',{title:'Approve grant compliance',description:'Compliance-reviewer approval of a grant before payment authorization. NQD grants also require approved diligence.',inputSchema:{grantId:z.string().uuid()},annotations:WRITE_LOCAL},async({grantId})=>textResult('Grant compliance approved.',await workflow.approveCompliance(grantId,context)));
 server.registerTool('dispatch_plan_offers',{title:'Dispatch approved grant offers',description:'Foundation-approver action that checks public CRA revocation evidence for registered charities, creates one-time offer links, and sends via the configured notification provider. This does not move money.',inputSchema:{planId:z.string().uuid()},annotations:WRITE_EXTERNAL},async({planId})=>textResult('Offer dispatch attempted; review each grant result.',await workflow.dispatchPlan(planId,context)));
 server.registerTool('list_my_grant_offers',{title:'List my recipient grant offers',description:'List offered/accepted/declined grants for organizations the authenticated recipient admin controls.',inputSchema:{},annotations:READ_ONLY},async()=>textResult('Recipient grant offers retrieved.',{grants:await workflow.myOffers(context)}));
 server.registerTool('respond_to_grant_offer',{title:'Accept or decline grant offer',description:'Authenticated recipient-admin acceptance or decline. Acceptance records versioned consent but does not authorize or execute payment.',inputSchema:{grantId:z.string().uuid(),accept:z.boolean(),note:z.string().max(4000).default('')},annotations:WRITE_LOCAL},async input=>textResult(input.accept?'Grant offer accepted; no payment has been authorized.':'Grant offer declined.',await workflow.respondAuthenticated(input,context)));
 server.registerTool('set_external_banking_verification',{title:'Record external banking verification',description:'Payment-operator recording of an external banking-verification status/reference for an accepted grant. Bank account/card coordinates are not stored.',inputSchema:{grantId:z.string().uuid(),status:z.enum(['pending_external_verification','verified_external','rejected']),reference:z.string().max(2000).default('')},annotations:WRITE_LOCAL},async input=>textResult('External banking-verification state recorded; no bank coordinates were stored.',await workflow.setBankingVerification(input,context)));
 server.registerTool('create_payment_intent',{title:'Create payment intent',description:'Payment-operator creation of a non-executing payment intent after recipient acceptance and external banking verification.',inputSchema:{grantId:z.string().uuid()},annotations:WRITE_LOCAL},async({grantId})=>textResult('Payment intent created. No money moved and a different payment operator must authorize it.',await workflow.createPaymentIntent(grantId,context)));
 server.registerTool('authorize_payment_intent',{title:'Authorize payment intent',description:'Second payment-operator authorization. Requires fresh eligible recipient status and approved compliance; the payment creator cannot authorize the same intent. The app still does not move money.',inputSchema:{paymentIntentId:z.string().uuid()},annotations:WRITE_LOCAL},async({paymentIntentId})=>textResult('Payment intent authorized for external/manual execution. No money moved by this app.',await workflow.authorizePaymentIntent(paymentIntentId,context)));
 server.registerTool('record_external_payment',{title:'Record externally executed payment',description:'Record a payment already executed outside the clearing house, using its external payment reference. This tool cannot initiate a bank transfer.',inputSchema:{paymentIntentId:z.string().uuid(),externalPaymentReference:z.string().min(1).max(2000)},annotations:WRITE_LOCAL},async input=>textResult('External payment reference recorded; the clearing house did not move money.',await workflow.recordExternalPayment(input,context)));
 server.registerTool('prepare_grant_reporting',{title:'Prepare CRA reporting record',description:'Prepare a reporting record for a paid grant. Non-qualified-donee classification aggregates fiscal-year grants before applying the reporting threshold. No CRA filing is submitted.',inputSchema:{grantId:z.string().uuid(),fiscalYear:z.number().int().min(2000).max(2100),t3010Version:z.string().max(100).default('current-review-required')},annotations:WRITE_LOCAL},async input=>textResult('Reporting record prepared for review; no CRA filing was submitted.',await workflow.prepareReporting(input,context)));
 server.registerTool('mark_grant_reported',{title:'Mark grant reported after external CRA filing',description:'Compliance-reviewer action that records an external filing reference and marks the grant reported. It does not submit a CRA return.',inputSchema:{reportingRecordId:z.string().uuid(),filingReference:z.string().min(1).max(2000)},annotations:WRITE_LOCAL},async input=>textResult('External filing reference recorded and grant marked reported.',await workflow.markReported(input,context)));
 server.registerTool('audit_events',{title:'Read tamper-evident audit log',description:'System-admin or auditor access to application audit entries. The log is HMAC chained by the persistence layer.',inputSchema:{limit:z.number().int().min(1).max(500).default(100),resourceType:z.string().max(100).optional(),resourceId:z.string().max(200).optional()},annotations:READ_ONLY},async input=>{if(!context)throw new Error('Authentication required.');if(!hasPermission(context.identity.roles,PERMISSIONS.AUDIT_READ))throw new Error('Auditor or system-admin role is required.');return textResult('Audit entries retrieved.',{events:await store.listAudit(input)});});
}
