import { createHash, randomBytes } from 'node:crypto';
import { GRANT_STATES, transitionGrant } from './grant_lifecycle.mjs';
import { PERMISSIONS, ROLES, hasPermission, requirePermission } from '../security/rbac.mjs';
import { RECIPIENT_TYPES, classifyGrantReporting } from '../compliance/reporting.mjs';
import { ManualPaymentAdapter, DisabledPaymentAdapter } from '../integrations/payment.mjs';
import { checkCraPublicEvidence } from '../status/cra-evidence.mjs';

const normalizeBn=value=>String(value||'').toUpperCase().replace(/[\s-]/g,'');
const tokenHash=token=>createHash('sha256').update(token).digest('hex');
function riskFromDiligence({relationshipExperience,amountCad,durationMonths,writtenAgreement,separateLedger,researchSummary}){let points=0;if(relationshipExperience==='none')points+=2;else if(relationshipExperience==='some')points+=1;if(amountCad>250000)points+=2;else if(amountCad>50000)points+=1;if(durationMonths>24)points+=2;else if(durationMonths>12)points+=1;if(!writtenAgreement)points+=2;if(!separateLedger)points+=1;if(!String(researchSummary||'').trim())points+=1;return{points,risk:points>=6?'high':points>=3?'medium':'low'};}

export class WorkflowService{
  constructor({store,t3010Repository,config,notificationAdapter}){this.store=store;this.t3010=t3010Repository;this.config=config;this.notification=notificationAdapter;this.payment=config.paymentProvider==='manual'?new ManualPaymentAdapter():new DisabledPaymentAdapter();}
  async context(identity){if(!identity)return null;const user=await this.store.ensureUser(identity);const memberships=await this.store.membershipsForUser(user.id);return{identity,user,memberships};}
  rolesForOrganization(context,org){if(!context)return[];if(context.identity.roles.includes(ROLES.SYSTEM_ADMIN))return[ROLES.SYSTEM_ADMIN];const roles=new Set();if(context.identity.organizationBns.includes(org.businessNumber))for(const role of context.identity.roles)roles.add(role);for(const membership of context.memberships)if(membership.organizationId===org.id)roles.add(membership.role);return[...roles];}
  actorForOrganization(context,org,permission){if(!context)throw Object.assign(new Error('Authentication is required.'),{statusCode:401});const actor={id:context.user.id,roles:this.rolesForOrganization(context,org),organizationId:org.id};requirePermission(actor,permission);return actor;}
  systemActor(context){if(!context)throw Object.assign(new Error('Authentication is required.'),{statusCode:401});const actor={id:context.user.id,roles:context.identity.roles,organizationId:null};requirePermission(actor,PERMISSIONS.MANAGE_IDENTITY);if(!actor.roles.includes(ROLES.SYSTEM_ADMIN))throw new Error('System administrator role is required.');return actor;}

  async ensureOrganizationFromT3010(bn,actor=null){const normalized=normalizeBn(bn);let org=await this.store.findOrganizationByBn(normalized);if(org)return org;const charity=this.t3010?.loaded?this.t3010.charityProfile(normalized):null;const foundation=this.t3010?.loaded?this.t3010.foundationProfile(normalized):null;const profile=foundation||charity;if(!profile)throw new Error(`No organization ${normalized} exists in workflow storage or loaded T3010 data.`);return this.store.upsertOrganization({businessNumber:normalized,legalName:profile.name||normalized,organizationType:foundation?'foundation':'registered_charity',province:profile.province||null,publicProfile:{source:'CRA T3010/Open Government Canada',sourceYear:profile.sourceYear,mission:profile.programDescriptions||[],website:profile.website||''}},actor);}
  async upsertOrganization(input,context){const actor=this.systemActor(context);return this.store.upsertOrganization({businessNumber:input.businessNumber||null,legalName:input.legalName,organizationType:input.organizationType,province:input.province||null,publicProfile:input.publicProfile||{},privateProfile:input.privateProfile===undefined?undefined:input.privateProfile},actor);}
  async requestClaim({businessNumber,evidence={}},context){if(!context)throw Object.assign(new Error('Authentication is required.'),{statusCode:401});const org=await this.ensureOrganizationFromT3010(businessNumber);return this.store.createRecipientClaim({organizationId:org.id,userId:context.user.id,evidence},{id:context.user.id,roles:context.identity.roles});}
  async reviewClaim({claimId,approve,note=''},context){const actor=this.systemActor(context);return this.store.reviewRecipientClaim({claimId,approve,note},actor,ROLES.RECIPIENT_ADMIN);}
  async updateRecipientProfile({businessNumber,publicProfile={},contact={}},context){const org=await this.ensureOrganizationFromT3010(businessNumber);const actor=this.actorForOrganization(context,org,PERMISSIONS.READ_PRIVATE_ORG);if(!hasPermission(actor.roles,PERMISSIONS.MANAGE_IDENTITY)&&!actor.roles.includes(ROLES.SYSTEM_ADMIN))throw new Error('Recipient-admin or system-admin permission is required.');const updated=await this.store.upsertOrganization({businessNumber:org.businessNumber,legalName:org.legalName,organizationType:org.organizationType,province:org.province,publicProfile:{...(org.publicProfile||{}),...publicProfile}},actor);await this.store.updateOrganizationPrivateProfile(org.id,current=>({...current,contact:{...(current.contact||{}),...contact}}),actor);return updated;}

  async createPlan({foundationBn,title,focus='',totalBudgetCad},context){const foundation=await this.ensureOrganizationFromT3010(foundationBn);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.PROPOSE_GRANT);return this.store.createPlan({foundationOrgId:foundation.id,title,focus,totalBudgetCad,createdBy:actor.id},actor);}
  async addGrant({planId,recipientBn,amountCad,purpose,recipientType='qualified_donee',rationale='',restrictionType='unrestricted'},context){const plan=await this.store.getPlan(planId);if(!plan)throw new Error('Allocation plan not found.');const foundation=await this.store.findOrganizationById(plan.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.PROPOSE_GRANT);let recipient=await this.store.findOrganizationByBn(recipientBn);if(!recipient&&recipientType===RECIPIENT_TYPES.QUALIFIED_DONEE)recipient=await this.ensureOrganizationFromT3010(recipientBn,actor);if(!recipient)throw new Error('Non-qualified donees must have an operator-created organization profile before a grant can be drafted.');const expectedType=recipientType===RECIPIENT_TYPES.NON_QUALIFIED_DONEE?'non_qualified_donee':'registered_charity';if(recipient.organizationType!==expectedType&&!(recipientType===RECIPIENT_TYPES.QUALIFIED_DONEE&&recipient.organizationType==='registered_charity'))throw new Error(`Recipient organization type ${recipient.organizationType} does not match ${recipientType}.`);return this.store.createGrant({planId,foundationOrgId:foundation.id,recipientOrgId:recipient.id,amountCad,purpose,recipientType,rationale,restrictionType},actor);}
  async draftMatchedPlan({foundationBn,title,focus='',province='',totalBudgetCad,minGrantCad=25000,maxGrantCad=150000,recipientLimit=50},context){if(!this.t3010?.loaded)throw new Error('T3010 data is required for matched plan drafting.');if(minGrantCad<=0||maxGrantCad<minGrantCad)throw new Error('Invalid grant bounds.');const plan=await this.createPlan({foundationBn,title,focus,totalBudgetCad},context);const foundation=await this.store.findOrganizationById(plan.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.PROPOSE_GRANT);const match=this.t3010.matchFoundation({foundationBn:normalizeBn(foundationBn),focus,province,limit:recipientLimit});let remaining=Number(totalBudgetCad);const created=[];for(let i=0;i<match.matches.length&&remaining>=minGrantCad;i++){const left=match.matches.length-i;const target=Math.min(maxGrantCad,Math.max(minGrantCad,remaining/left));const amount=Math.min(target,remaining);const candidate=match.matches[i];const recipient=await this.ensureOrganizationFromT3010(candidate.bn,actor);created.push(await this.store.createGrant({planId:plan.id,foundationOrgId:foundation.id,recipientOrgId:recipient.id,amountCad:Number(amount.toFixed(2)),purpose:focus||'General charitable purposes aligned with the foundation mandate',recipientType:RECIPIENT_TYPES.QUALIFIED_DONEE,rationale:candidate.rationale||'',restrictionType:'unrestricted'},actor));remaining-=amount;}return{plan:await this.store.getPlan(plan.id),matchesUsed:created.length,unallocatedCad:Number(remaining.toFixed(2)),matchEvidence:{confidence:match.confidence,evidenceTokens:match.evidenceTokens}};}

  async transitionOneGrant(grant,nextState,actor,input={},set={}){const recipientStatus=await this.store.latestStatusCheck(grant.recipient_org_id);const domain={id:grant.id,state:grant.state,foundationOrgId:grant.foundation_org_id,recipientOrgId:grant.recipient_org_id,amountCad:Number(grant.amount_cad),purpose:grant.purpose,proposedBy:grant.proposed_by,compliance:{decision:grant.compliance_decision},recipientStatus:recipientStatus?{status:recipientStatus.status,verifiedAt:recipientStatus.verified_at}:null};const next=transitionGrant(domain,nextState,actor,input,{maxStatusAgeHours:this.config.craStatusMaxAgeHours,requireSeparationOfDuties:this.config.requireSeparationOfDuties});return this.store.commitGrantTransition({grantId:grant.id,expectedState:grant.state,nextState,actorUserId:/^[0-9a-f-]{36}$/i.test(actor.id)?actor.id:null,event:next.lastEvent,set},actor);}
  async proposePlan(planId,context){const plan=await this.store.getPlan(planId);if(!plan)throw new Error('Allocation plan not found.');const foundation=await this.store.findOrganizationById(plan.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.PROPOSE_GRANT);if(plan.state!=='draft'||!plan.grants.length)throw new Error('Only a non-empty draft plan can be proposed.');for(const grant of plan.grants)await this.transitionOneGrant(grant,GRANT_STATES.PROPOSED,actor,{idempotencyKey:`plan:${planId}:grant:${grant.id}:proposed`},{proposedBy:actor.id});return this.store.setPlanState({planId,expectedState:'draft',nextState:'proposed'},actor);}
  async approvePlan(planId,context){const plan=await this.store.getPlan(planId);if(!plan)throw new Error('Allocation plan not found.');const foundation=await this.store.findOrganizationById(plan.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.APPROVE_GRANT);if(plan.created_by===actor.id)throw new Error('Separation of duties: plan creator cannot approve the same plan.');for(const grant of plan.grants){if(grant.recipient_type===RECIPIENT_TYPES.NON_QUALIFIED_DONEE){const diligence=await this.store.getDiligence(grant.id);if(!diligence||diligence.status!=='approved')throw new Error(`Non-qualified-donee grant ${grant.id} requires approved diligence before plan approval.`);}await this.transitionOneGrant(grant,GRANT_STATES.APPROVED,actor,{idempotencyKey:`plan:${planId}:grant:${grant.id}:approved`},{approvedBy:actor.id});}return this.store.setPlanState({planId,expectedState:'proposed',nextState:'approved',approvedBy:actor.id},actor);}

  async prepareDiligence({grantId,charitablePurposeAlignment,activityDescription,activityLocation='',durationMonths=12,relationshipExperience='none',researchSummary='',writtenAgreement=true,reportingPlan='final_report',periodicTransfers=false,separateLedger=true,notes=''},context){const grant=await this.store.getGrant(grantId);if(!grant)throw new Error('Grant not found.');if(grant.recipient_type!==RECIPIENT_TYPES.NON_QUALIFIED_DONEE)throw new Error('Diligence tool is for non-qualified-donee grants.');const foundation=await this.store.findOrganizationById(grant.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.PROPOSE_GRANT);const{points,risk}=riskFromDiligence({relationshipExperience,amountCad:Number(grant.amount_cad),durationMonths,writtenAgreement,separateLedger,researchSummary});const assessment={charitablePurposeAlignment,activityDescription,activityLocation,durationMonths,relationshipExperience,researchSummary,writtenAgreement,reportingPlan,periodicTransfers,separateLedger,notes,riskPoints:points,model:'reasonable_flexible_proportionate_due_diligence'};return this.store.upsertDiligence({grantId,assessment,recommendedRisk:risk},actor);}
  async approveDiligence(grantId,context){const grant=await this.store.getGrant(grantId);if(!grant)throw new Error('Grant not found.');const foundation=await this.store.findOrganizationById(grant.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.REVIEW_COMPLIANCE);return this.store.approveDiligence(grantId,actor);}
  async recordStatusVerification({grantId,status,source,sourceRecordId=null,evidence={}},context){const grant=await this.store.getGrant(grantId);if(!grant)throw new Error('Grant not found.');const foundation=await this.store.findOrganizationById(grant.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.REVIEW_COMPLIANCE);const verifiedAt=new Date();const expiresAt=new Date(verifiedAt.getTime()+this.config.craStatusMaxAgeHours*3600_000);return this.store.recordStatusCheck({organizationId:grant.recipient_org_id,source,sourceRecordId,status,evidence:{...evidence,grantId},verifiedAt,expiresAt},actor);}
  async approveCompliance(grantId,context){const grant=await this.store.getGrant(grantId);if(!grant)throw new Error('Grant not found.');const foundation=await this.store.findOrganizationById(grant.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.REVIEW_COMPLIANCE);if(grant.recipient_type===RECIPIENT_TYPES.NON_QUALIFIED_DONEE){const diligence=await this.store.getDiligence(grant.id);if(!diligence||diligence.status!=='approved')throw new Error('Approved non-qualified-donee diligence is required before compliance approval.');}return this.store.setComplianceDecision(grantId,'approved',actor);}
  async publicStatusEvidence(recipientBn){const profile=this.t3010?.loaded?this.t3010.charityProfile(normalizeBn(recipientBn)):null;return checkCraPublicEvidence({businessNumber:recipientBn,t3010Profile:profile});}

  async createOfferLink(grant,actor,ttlHours=336){const token=randomBytes(32).toString('base64url');const expiresAt=new Date(Date.now()+ttlHours*3600_000);const record=await this.store.createOfferToken({grantId:grant.id,tokenHash:tokenHash(token),expiresAt},actor);return{record,url:`${String(this.config.publicBaseUrl||'').replace(/\/$/,'')}/offers/${grant.id}?token=${encodeURIComponent(token)}`};}
  async dispatchPlan(planId,context){const plan=await this.store.getPlan(planId);if(!plan)throw new Error('Allocation plan not found.');const foundation=await this.store.findOrganizationById(plan.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.OFFER_GRANT);if(!['approved','partial_offered'].includes(plan.state))throw new Error('Plan must be approved before offers can be dispatched.');const results=[];for(const grant of plan.grants){if(grant.state!==GRANT_STATES.APPROVED)continue;const recipient=await this.store.getOrganizationInternal(grant.recipient_org_id);if(!recipient){results.push({grantId:grant.id,status:'blocked',reason:'recipient profile missing'});continue;}if(grant.recipient_type===RECIPIENT_TYPES.QUALIFIED_DONEE){const evidence=await this.publicStatusEvidence(recipient.businessNumber);if(evidence.revocationEvidenceFound){results.push({grantId:grant.id,status:'blocked',reason:'published revocation evidence found'});continue;}}const contact=recipient.privateProfile?.contact||{};const destinations=[];if(contact.email)destinations.push({channel:'email',recipient:contact.email});if(contact.phone)destinations.push({channel:'sms',recipient:contact.phone});if(!destinations.length){results.push({grantId:grant.id,status:'needs_contact'});continue;}const link=await this.createOfferLink(grant,actor);const body=`${foundation.legalName} has offered CAD ${Number(grant.amount_cad).toLocaleString('en-CA')} to ${recipient.legalName}. Purpose: ${grant.purpose}. Review and respond: ${link.url}`;let delivered=false;for(const dest of destinations){const outbox=await this.store.enqueueNotification({grantId:grant.id,...dest,subject:'Grant offer',template:'grant_offer',payload:{body,offerUrl:link.url,amountCad:Number(grant.amount_cad),purpose:grant.purpose},idempotencyKey:`grant:${grant.id}:offer:${dest.channel}:${dest.recipient}`},actor);try{const sent=await this.notification.send({...dest,subject:'Grant offer',body,metadata:{grantId:grant.id}});await this.store.markNotification({id:outbox.id,status:sent.delivered?'sent':'failed',providerMessageId:sent.providerMessageId||null,lastError:sent.delivered?null:sent.status},actor);delivered||=Boolean(sent.delivered);}catch(error){await this.store.markNotification({id:outbox.id,status:'failed',lastError:error.message},actor);}}if(delivered){await this.transitionOneGrant(grant,GRANT_STATES.OFFERED,actor,{idempotencyKey:`grant:${grant.id}:offered`});results.push({grantId:grant.id,status:'offered'});}else results.push({grantId:grant.id,status:'notification_failed'});}const refreshed=await this.store.getPlan(planId);const remaining=refreshed.grants.filter(grant=>grant.state===GRANT_STATES.APPROVED).length;const nextState=remaining?'partial_offered':'offered';const updatedPlan=plan.state===nextState?refreshed:await this.store.setPlanState({planId,expectedState:plan.state,nextState},actor);return{plan:updatedPlan,results,remainingApprovedGrants:remaining};}

  async inspectOffer({grantId,token}){const access=await this.store.inspectOfferToken(tokenHash(token));if(!access||access.grant_id!==grantId)throw new Error('Invalid offer token.');if(access.used_at)throw new Error('Offer token has already been used.');if(new Date(access.expires_at).getTime()<=Date.now())throw new Error('Offer token has expired.');const grant=await this.store.getGrant(grantId);if(!grant||grant.state!==GRANT_STATES.OFFERED)throw new Error('Grant offer is no longer open.');const foundation=await this.store.findOrganizationById(grant.foundation_org_id);const recipient=await this.store.findOrganizationById(grant.recipient_org_id);return{access,grant,foundation,recipient};}
  async respondByToken({grantId,token,accept,note=''}){const inspected=await this.inspectOffer({grantId,token});const access=await this.store.consumeOfferToken(tokenHash(token));const actor={id:access.id,roles:[ROLES.RECIPIENT_ADMIN],organizationId:inspected.grant.recipient_org_id};const nextState=accept?GRANT_STATES.ACCEPTED:GRANT_STATES.DECLINED;const result=await this.transitionOneGrant(inspected.grant,nextState,actor,{idempotencyKey:`offer-token:${access.id}:${nextState}`,acceptedTerms:Boolean(accept),note},{acceptedBy:null});await this.store.createConsent({grantId,userId:null,termsVersion:process.env.GRANT_TERMS_VERSION||'2026-08',accepted:Boolean(accept),metadata:{note},acceptanceMethod:'offer_token',offerTokenId:access.id},actor);return result.grant;}
  async myOffers(context){if(!context)throw Object.assign(new Error('Authentication is required.'),{statusCode:401});const recipientOrgIds=context.memberships.filter(m=>m.role===ROLES.RECIPIENT_ADMIN).map(m=>m.organizationId);for(const bn of context.identity.organizationBns){const org=await this.store.findOrganizationByBn(bn);if(org&&context.identity.roles.includes(ROLES.RECIPIENT_ADMIN))recipientOrgIds.push(org.id);}if(!recipientOrgIds.length)return[];const{rows}=await this.store.query("SELECT * FROM grants WHERE recipient_org_id = ANY($1::uuid[]) AND state IN ('offered','accepted','declined') ORDER BY updated_at DESC",[[...new Set(recipientOrgIds)]]);return rows;}
  async respondAuthenticated({grantId,accept,note=''},context){const grant=await this.store.getGrant(grantId);if(!grant)throw new Error('Grant not found.');const recipient=await this.store.findOrganizationById(grant.recipient_org_id);const actor=this.actorForOrganization(context,recipient,accept?PERMISSIONS.ACCEPT_GRANT:PERMISSIONS.DECLINE_GRANT);const nextState=accept?GRANT_STATES.ACCEPTED:GRANT_STATES.DECLINED;const result=await this.transitionOneGrant(grant,nextState,actor,{idempotencyKey:`user:${actor.id}:grant:${grantId}:${nextState}`,acceptedTerms:Boolean(accept),note},{acceptedBy:accept?actor.id:grant.accepted_by});await this.store.createConsent({grantId,userId:actor.id,termsVersion:process.env.GRANT_TERMS_VERSION||'2026-08',accepted:Boolean(accept),metadata:{note}},actor);return result.grant;}

  async setBankingVerification({grantId,status,reference},context){const grant=await this.store.getGrant(grantId);if(!grant)throw new Error('Grant not found.');if(grant.state!==GRANT_STATES.ACCEPTED)throw new Error('Banking verification can only be recorded after recipient acceptance.');const foundation=await this.store.findOrganizationById(grant.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.AUTHORIZE_PAYMENT);const allowed=new Set(['pending_external_verification','verified_external','rejected']);if(!allowed.has(status))throw new Error(`Unsupported banking verification status ${status}.`);const privateProfile=await this.store.updateOrganizationPrivateProfile(grant.recipient_org_id,current=>({...current,bankingVerification:{status,reference:String(reference||''),verifiedAt:new Date().toISOString(),grantId}}),actor);return{status:privateProfile.bankingVerification.status,reference:privateProfile.bankingVerification.reference,bankCoordinatesStored:false};}
  async createPaymentIntent(grantId,context){const grant=await this.store.getGrant(grantId);if(!grant)throw new Error('Grant not found.');const foundation=await this.store.findOrganizationById(grant.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.AUTHORIZE_PAYMENT);if(grant.state!==GRANT_STATES.ACCEPTED)throw new Error('Payment intent requires an accepted grant.');const recipient=await this.store.getOrganizationInternal(grant.recipient_org_id);if(recipient.privateProfile?.bankingVerification?.status!=='verified_external')throw new Error('External banking verification is required before creating a payment intent.');return this.store.createPaymentIntent({grantId,provider:this.config.paymentProvider,amountCad:Number(grant.amount_cad),createdBy:actor.id},actor);}
  async authorizePaymentIntent(paymentIntentId,context){const intent=await this.store.getPaymentIntent(paymentIntentId);if(!intent)throw new Error('Payment intent not found.');const grant=await this.store.getGrant(intent.grant_id);const foundation=await this.store.findOrganizationById(grant.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.AUTHORIZE_PAYMENT);if(intent.created_by===actor.id)throw new Error('Separation of duties: payment-intent creator cannot authorize the same intent.');const adapterResult=await this.payment.authorize({grantId:grant.id,amountCad:Number(grant.amount_cad)});if(!adapterResult.authorized)throw new Error('Payment provider is disabled.');const transitioned=await this.transitionOneGrant(grant,GRANT_STATES.PAYMENT_AUTHORIZED,actor,{idempotencyKey:`payment-intent:${intent.id}:authorized`});const updated=await this.store.authorizePaymentIntent({id:intent.id,authorizedBy:actor.id,status:'external_execution_required'},actor);return{paymentIntent:updated,grant:transitioned.grant,moneyMovedByThisApp:false};}
  async recordExternalPayment({paymentIntentId,externalPaymentReference},context){const intent=await this.store.getPaymentIntent(paymentIntentId);if(!intent)throw new Error('Payment intent not found.');const grant=await this.store.getGrant(intent.grant_id);const foundation=await this.store.findOrganizationById(grant.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.RECORD_PAYMENT);const adapter=await this.payment.recordExternalPayment({grantId:grant.id,externalPaymentReference});const recorded=await this.store.recordPaymentIntent({id:intent.id,externalReference:externalPaymentReference},actor);const transitioned=await this.transitionOneGrant(grant,GRANT_STATES.PAID,actor,{idempotencyKey:`payment-intent:${intent.id}:recorded`,externalPaymentReference});return{paymentIntent:recorded,grant:transitioned.grant,adapter};}

  async prepareReporting({grantId,fiscalYear,t3010Version='current-review-required'},context){const grant=await this.store.getGrant(grantId);if(!grant)throw new Error('Grant not found.');if(grant.state!==GRANT_STATES.PAID)throw new Error('Reporting record can be prepared only after payment is recorded.');const foundation=await this.store.findOrganizationById(grant.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.EXPORT_REPORTING);const fiscalGrants=await this.store.grantsForRecipientFiscalYear(grant.recipient_org_id,fiscalYear);const classification=classifyGrantReporting({recipientType:grant.recipient_type,recipientOrgId:grant.recipient_org_id,fiscalYearGrants:fiscalGrants.map(row=>({recipientOrgId:row.recipient_org_id,amountCad:Number(row.amount_cad)}))});return this.store.createReportingRecord({grantId,fiscalYear,reportingRoute:classification.route,t3010Version,t1441Required:classification.t1441Required,payload:{classification,grantSnapshot:grant}},actor);}
  async markReported({reportingRecordId,filingReference},context){const record=(await this.store.query('SELECT * FROM reporting_records WHERE id=$1',[reportingRecordId])).rows[0];if(!record)throw new Error('Reporting record not found.');const grant=await this.store.getGrant(record.grant_id);const foundation=await this.store.findOrganizationById(grant.foundation_org_id);const actor=this.actorForOrganization(context,foundation,PERMISSIONS.MARK_REPORTED);const filed=await this.store.markReportingFiled({id:reportingRecordId,filingReference},actor);const transitioned=await this.transitionOneGrant(grant,GRANT_STATES.REPORTED,actor,{idempotencyKey:`reporting:${reportingRecordId}:filed`,reportingRecordId});return{reportingRecord:filed,grant:transitioned.grant};}
}
